/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plsaj.Login;

import plsaj.Font.CustomFont;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Wahyu Khoirur Rizal
 */
public class formLogin extends javax.swing.JFrame {
//    
    int xx, xy;
    CustomFont Poppins = new CustomFont();
    
    /**
     * Creates new form formLogin
     */
    private boolean over;
    private javax.swing.JMenu XMenuBar = XMenuBar = new javax.swing.JMenu(); 
    public formLogin() {
        initComponents();
     
    }
    
    void bersih(){
        usernameText.setText("enter your username");
        passwordText.setText("enter your username");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        myAccount = new javax.swing.JLabel();
        buttonX = new plsaj.Custom.FButton();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new plsaj.Custom.FTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordText = new plsaj.Custom.FTextField();
        ForgotPassword = new javax.swing.JLabel();
        buttonLogin = new plsaj.Custom.FButton2();
        buttonSignUp = new plsaj.Custom.FButton1();
        backgroundLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setOpaque(false);
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plsaj/Img/account.png"))); // NOI18N
        loginPanel.add(myAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        buttonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plsaj/Img/button-x.png"))); // NOI18N
        buttonX.setRadiusBorder(17);
        buttonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonXMouseClicked(evt);
            }
        });
        loginPanel.add(buttonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 40, 40));

        usernameLabel.setFont(Poppins.getPoppinsSemiBold().deriveFont(18f));
        usernameLabel.setText("Username");
        loginPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 40));

        usernameText.setForeground(new java.awt.Color(102, 102, 102));
        usernameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameText.setText("enter your username");
        usernameText.setFont(Poppins.getPoppinsMedium().deriveFont(15f));
        usernameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFocusLost(evt);
            }
        });
        loginPanel.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 360, 45));

        passwordLabel.setFont(Poppins.getPoppinsSemiBold().deriveFont(18f));
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 40));

        passwordText.setForeground(new java.awt.Color(102, 102, 102));
        passwordText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordText.setText("enter your password");
        passwordText.setFont(Poppins.getPoppinsMedium().deriveFont(15f));
        passwordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFocusLost(evt);
            }
        });
        loginPanel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 360, 45));

        ForgotPassword.setFont(Poppins.getPoppinsSemiBold().deriveFont(13f));
        ForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ForgotPassword.setText("Fotgot Password?");
        loginPanel.add(ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 360, 40));

        buttonLogin.setText("Log In");
        buttonLogin.setFillClick(new java.awt.Color(19, 54, 44));
        buttonLogin.setFillOver(new java.awt.Color(31, 87, 70));
        buttonLogin.setFont(Poppins.getPoppinsSemiBold().deriveFont(15f));
        buttonLogin.setRadiusBorder(19);
        loginPanel.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 360, 45));

        buttonSignUp.setForeground(new java.awt.Color(102, 102, 102));
        buttonSignUp.setText("Sign Up");
        buttonSignUp.setFocusable(false);
        buttonSignUp.setFont(Poppins.getPoppinsSemiBold().deriveFont(15f));
        buttonSignUp.setRadiusBorder(19);
        buttonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignUpActionPerformed(evt);
            }
        });
        loginPanel.add(buttonSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 360, 45));

        bgPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 650));

        backgroundLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plsaj/Img/bg_login.png"))); // NOI18N
        bgPanel.add(backgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
        
    }//GEN-LAST:event_formMousePressed

    private void buttonXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "KONFIRMASI KELUAR",
                JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonXMouseClicked

    private void buttonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSignUpActionPerformed

    private void usernameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusGained
        // TODO add your handling code here:
        String username=usernameText.getText();
        if (username.equals("enter your username")){
            usernameText.setText("");
        }
    
    }//GEN-LAST:event_usernameTextFocusGained

    private void passwordTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFocusGained
        // TODO add your handling code here:
        String pass=passwordText.getText();
        if (pass.equals("enter your password")){
            passwordText.setText("");
        }
    }//GEN-LAST:event_passwordTextFocusGained

    private void passwordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFocusLost
        // TODO add your handling code here:
        String pass=passwordText.getText();
        if(pass.equals("")|pass.equals("enter your password")){
            passwordText.setText("enter your password");
        }
    }//GEN-LAST:event_passwordTextFocusLost

    private void usernameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusLost
        // TODO add your handling code here:
        String username=usernameText.getText();
        if(username.equals("")|username.equals("enter your username")){
            usernameText.setText("enter your username");
        }
    }//GEN-LAST:event_usernameTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JLabel backgroundLogin;
    private javax.swing.JPanel bgPanel;
    private plsaj.Custom.FButton2 buttonLogin;
    private plsaj.Custom.FButton1 buttonSignUp;
    private plsaj.Custom.FButton buttonX;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel myAccount;
    private javax.swing.JLabel passwordLabel;
    private plsaj.Custom.FTextField passwordText;
    private javax.swing.JLabel usernameLabel;
    private plsaj.Custom.FTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
